services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  JWeiland\SyncCropAreas\:
    resource: '../Classes/*'

  JWeiland\SyncCropAreas\Hook\DataHandlerHook:
    public: true

  # Register commands for sync_crop_areas
  JWeiland\SyncCropAreas\Command\SynchronizeCropVariantsCommand:
    tags:
      - name: 'console.command'
        command: 'sync_crop_areas:sync'
        description: 'Use this service to synchronize first found cropVariants to the other defined cropVariants'
